service: sso-server

frameworkVersion: '3'

package: 
  individually: true
  patterns:
    - sso.yml
    - global-bundle.pem

custom:
  serverless-offline:
    httpPort: 3000

  variables:
    role: arn:aws:iam::106373595693:role/i-am-a-god-role
    bucket: boybetby-bucket

provider: 
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  deploymentMethod: changesets
  memorySize: 256
  timeout: 10
  versionFunctions: false
  logRetentionInDays: 7
  stackName: ${self:service}-${self:provider.stage}
  role: ${self:custom.variables.role}
  deploymentBucket:
    name: ${self:custom.variables.bucket}
  vpc:
    securityGroupIds:
      - sg-0a470c17263a78b5b # public
    subnetIds:
      # - subnet-01fcf68eb635e0d3b # public
      # - subnet-072cfa9f32ebc3347 # public
      - subnet-06e4be73a87c936a8 # private
      - subnet-0340b0e9043a99096 # private
      - subnet-000a1c887c1f0b499 # private
  httpApi:
    cors: true
    metrics: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

functions: ${file(functions.yml):functions}
